# Part 1: Data preprocessing

In [1]:
#Importer les bibliothèques nécessaires
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import missingno as msno
import datetime as dt
#Importer les bibliothèques nécessaires

In [2]:
#Transformer nos données en une base de données pandas
#On a pas de colonne d'index dans le fichier csv
cars = pd.read_csv('wandaloo_cars.csv')
cars

,Brand,Model,Version,Price,Model year,Hand,Mileage,Fuel type,Transmission,Fiscal horsepower,...,Airbags,ABS,ESP,Traction control,Engine architecture,Engine displacement,City fuel consumption,Highway fuel consumption,Maximum speed,Fuel tank volume
0,MERCEDES,Classe C 2014,220 d,228.000 DH,2014.0,Seconde,144.500 km,Diesel,Automatique,8 cv,...,oui,oui,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN
1,MERCEDES,Classe C 2003,220 CDI,79.000 DH,2003.0,Seconde,350.000 km,Diesel,Manuelle,8 cv,...,oui,oui,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN
2,MERCEDES,Classe B 2013,180 d Urban,150.000 DH,2013.0,Seconde,144.000 km,Diesel,Manuelle,8 cv,...,oui,oui,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN
3,MERCEDES,Classe E 2006,Autre version,135.000 DH,2006.0,Seconde,248.000 km,Diesel,Automatique,9 cv,...,oui,oui,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN
4,MERCEDES,CLA Coupé 2014,220 CDI,240.000 DH,2014.0,Seconde,103.000 km,Diesel,Automatique,9 cv,...,oui,oui,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3124,VOLVO,XC90,NaN,630.000 DH * * Prix public,NaN,NaN,NaN,NaN,NaN,8 cv,...,7.0,oui,oui,oui,4 cylindres,1.969 cm³,"6,3 l/100 km","5,4 l/100 km",220 km/h,71 litre
3125,VOLVO,XC90,NaN,730.000 DH * * Prix public,NaN,NaN,NaN,NaN,NaN,8 cv,...,7.0,oui,oui,oui,4 cylindres,1.969 cm³,"6,3 l/100 km","5,4 l/100 km",220 km/h,71 litre
3126,VOLVO,XC90,NaN,850.000 DH * * Prix public,NaN,NaN,NaN,NaN,NaN,8 cv,...,7.0,oui,oui,oui,4 cylindres,1.969 cm³,"6,3 l/100 km","5,4 l/100 km",220 km/h,71 litre
3127,VOLVO,XC90,NaN,1.000.000 DH * * Prix public,NaN,NaN,NaN,NaN,NaN,11 cv,...,7.0,oui,oui,oui,4 cylindres,1.969 cm³,- l/100 km,- l/100 km,230 km/h,71 litre
3128,VOLVO,XC90,NaN,1.100.000 DH * * Prix public,NaN,NaN,NaN,NaN,NaN,11 cv,...,7.0,oui,oui,oui,4 cylindres,1.969 cm³,- l/100 km,- l/100 km,230 km/h,71 litre

In [3]:
#Imprimer la tête de notre dataframe pour avoir une vision sur nos données et ses problèmes
cars.head()

,Brand,Model,Version,Price,Model year,Hand,Mileage,Fuel type,Transmission,Fiscal horsepower,...,Airbags,ABS,ESP,Traction control,Engine architecture,Engine displacement,City fuel consumption,Highway fuel consumption,Maximum speed,Fuel tank volume
0,MERCEDES,Classe C 2014,220 d,228.000 DH,2014.0,Seconde,144.500 km,Diesel,Automatique,8 cv,...,oui,oui,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN
1,MERCEDES,Classe C 2003,220 CDI,79.000 DH,2003.0,Seconde,350.000 km,Diesel,Manuelle,8 cv,...,oui,oui,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN
2,MERCEDES,Classe B 2013,180 d Urban,150.000 DH,2013.0,Seconde,144.000 km,Diesel,Manuelle,8 cv,...,oui,oui,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN
3,MERCEDES,Classe E 2006,Autre version,135.000 DH,2006.0,Seconde,248.000 km,Diesel,Automatique,9 cv,...,oui,oui,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN
4,MERCEDES,CLA Coupé 2014,220 CDI,240.000 DH,2014.0,Seconde,103.000 km,Diesel,Automatique,9 cv,...,oui,oui,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
cars['Model']

0        Classe C 2014
1        Classe C 2003
2        Classe B 2013
3        Classe E 2006
4       CLA Coupé 2014
             ...
3124              XC90
3125              XC90
3126              XC90
3127              XC90
3128              XC90
Name: Model, Length: 3129, dtype: object

In [5]:
# Imprimer les types de données de nos colonnes
cars.dtypes

Brand                         object
Model                         object
Version                       object
Price                         object
Model year                   float64
Hand                          object
Mileage                       object
Fuel type                     object
Transmission                  object
Fiscal horsepower             object
Exterior color                object
Vehicle condition             object
Air conditioning              object
Electric windows              object
Electric seats                object
On-board computer             object
Start & Stop                  object
Cruise control                object
Automatic headlights          object
Rain sensor                   object
Steering wheel controls       object
Touchscreen display           object
Electric mirrors              object
Automatic trunk opening       object
Hands-free start              object
1/3-2/3 folding rear seat     object
Backup camera                 object
Bluetooth                     object
Aluminum wheels               object
Leather steering wheel        object
Daytime running lights        object
Roof rails                    object
Roof                          object
Airbags                       object
ABS                           object
ESP                           object
Traction control              object
Engine architecture           object
Engine displacement           object
City fuel consumption         object
Highway fuel consumption      object
Maximum speed                 object
Fuel tank volume              object
dtype: object

In [6]:
#Cette commande nous fournit :
#Le nombre de lignes et de colonnes dans le DataFrame.
#Les noms des colonnes et leurs types de données.
#Le nombre de valeurs non nulles dans chaque colonne.
#La quantité de mémoire utilisée par le DataFrame.
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3129 entries, 0 to 3128
Data columns (total 43 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Brand                      3063 non-null   object
 1   Model                      3063 non-null   object
 2   Version                    2180 non-null   object
 3   Price                      3063 non-null   object
 4   Model year                 2180 non-null   float64
 5   Hand                       2180 non-null   object
 6   Mileage                    2180 non-null   object
 7   Fuel type                  2166 non-null   object
 8   Transmission               2180 non-null   object
 9   Fiscal horsepower          3048 non-null   object
 10  Exterior color             2180 non-null   object
 11  Vehicle condition          2180 non-null   object
 12  Air conditioning           3048 non-null   object
 13  Electric windows           3048 non-null   object
 14  Electric seats             3028 non-null   object
 15  On-board computer          3048 non-null   object
 16  Start & Stop               3048 non-null   object
 17  Cruise control             3048 non-null   object
 18  Automatic headlights       3048 non-null   object
 19  Rain sensor                3048 non-null   object
 20  Steering wheel controls    3048 non-null   object
 21  Touchscreen display        3048 non-null   object
 22  Electric mirrors           3048 non-null   object
 23  Automatic trunk opening    2180 non-null   object
 24  Hands-free start           3048 non-null   object
 25  1/3-2/3 folding rear seat  3048 non-null   object
 26  Backup camera              3048 non-null   object
 27  Bluetooth                  3048 non-null   object
 28  Aluminum wheels            3048 non-null   object
 29  Leather steering wheel     3048 non-null   object
 30  Daytime running lights     3048 non-null   object
 31  Roof rails                 3048 non-null   object
 32  Roof                       3048 non-null   object
 33  Airbags                    3048 non-null   object
 34  ABS                        3048 non-null   object
 35  ESP                        3048 non-null   object
 36  Traction control           3048 non-null   object
 37  Engine architecture        845 non-null    object
 38  Engine displacement        845 non-null    object
 39  City fuel consumption      845 non-null    object
 40  Highway fuel consumption   845 non-null    object
 41  Maximum speed              868 non-null    object
 42  Fuel tank volume           845 non-null    object
dtypes: float64(1), object(42)
memory usage: 1.0+ MB

In [7]:
#Connaître le nombre exact de valeurs manquantes pour chaque colonne
cars.isna().sum()

Brand                          66
Model                          66
Version                       949
Price                          66
Model year                    949
Hand                          949
Mileage                       949
Fuel type                     963
Transmission                  949
Fiscal horsepower              81
Exterior color                949
Vehicle condition             949
Air conditioning               81
Electric windows               81
Electric seats                101
On-board computer              81
Start & Stop                   81
Cruise control                 81
Automatic headlights           81
Rain sensor                    81
Steering wheel controls        81
Touchscreen display            81
Electric mirrors               81
Automatic trunk opening       949
Hands-free start               81
1/3-2/3 folding rear seat      81
Backup camera                  81
Bluetooth                      81
Aluminum wheels                81
Leather steering wheel         81
Daytime running lights         81
Roof rails                     81
Roof                           81
Airbags                        81
ABS                            81
ESP                            81
Traction control               81
Engine architecture          2284
Engine displacement          2284
City fuel consumption        2284
Highway fuel consumption     2284
Maximum speed                2261
Fuel tank volume             2284
dtype: int64

# liste to do


. tâche 1 : diviser la colonne Model en deux colonnes Classe et Année
. tâche 2 : suprimer la colonne Année puisque c'est une duplication de la colonne Modèle
. tâche 3 : convertir le Price en proportion (flotteur)
. tâche 4 : convertir le Modèle en proportion (Datetime)

. tâche 5 : convertir le Kilométrage en proportion (flotteur)
. tâche 6 : convertir le Cylindrée en proportion (flotteur)





. tâche 8 : Supprimer les duplications 
. tâche 9 : Supprimer les lignes vides

In [8]:
#Diviser la colonne Model en deux
#L'argument n dans split() est utilisé pour spécifier le nombre maximum de séparateurs à utiliser lors de la division d'une chaîne de caractères.
model = cars['Model'].str.split(n=2, expand = True)

In [9]:
#Attribuer les colonnes crées aux colonnes Model et Année 
cars['Classe'] = model[0] + " " + model[1]
cars['Année'] = model[2]
# Imprimer l'en-tête et confirmer la création des nouvelles colonnes
cars.head(3000)

,Brand,Model,Version,Price,Model year,Hand,Mileage,Fuel type,Transmission,Fiscal horsepower,...,ESP,Traction control,Engine architecture,Engine displacement,City fuel consumption,Highway fuel consumption,Maximum speed,Fuel tank volume,Classe,Année
0,MERCEDES,Classe C 2014,220 d,228.000 DH,2014.0,Seconde,144.500 km,Diesel,Automatique,8 cv,...,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN,Classe C,2014
1,MERCEDES,Classe C 2003,220 CDI,79.000 DH,2003.0,Seconde,350.000 km,Diesel,Manuelle,8 cv,...,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN,Classe C,2003
2,MERCEDES,Classe B 2013,180 d Urban,150.000 DH,2013.0,Seconde,144.000 km,Diesel,Manuelle,8 cv,...,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN,Classe B,2013
3,MERCEDES,Classe E 2006,Autre version,135.000 DH,2006.0,Seconde,248.000 km,Diesel,Automatique,9 cv,...,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN,Classe E,2006
4,MERCEDES,CLA Coupé 2014,220 CDI,240.000 DH,2014.0,Seconde,103.000 km,Diesel,Automatique,9 cv,...,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN,CLA Coupé,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,SEAT,Arona,NaN,248.900 DH * promo,NaN,NaN,NaN,NaN,NaN,6 cv,...,oui,oui,4 cylindres,1.598 cm³,"5,4 l/100 km","4,2 l/100 km",178 km/h,40 litre,NaN,None
2996,SEAT,Arona,NaN,255.900 DH * promo,NaN,NaN,NaN,NaN,NaN,6 cv,...,oui,oui,4 cylindres,1.598 cm³,"5,4 l/100 km","4,2 l/100 km",178 km/h,40 litre,NaN,None
2997,SEAT,Ateca,NaN,297.900 DH * promo,NaN,NaN,NaN,NaN,NaN,8 cv,...,oui,oui,4 cylindres,2.998 cm³,"6,2 l/100 km","4,9 l/100 km",202 km/h,55 litre,NaN,None
2998,SEAT,Ateca,NaN,313.900 DH * promo,NaN,NaN,NaN,NaN,NaN,8 cv,...,oui,oui,4 cylindres,2.998 cm³,"6,2 l/100 km","4,9 l/100 km",202 km/h,55 litre,NaN,None
2999,SEAT,Ateca,NaN,330.900 DH * promo,NaN,NaN,NaN,NaN,NaN,8 cv,...,oui,oui,4 cylindres,2.998 cm³,"6,2 l/100 km","4,9 l/100 km",202 km/h,55 litre,NaN,None

In [10]:
# cars['Conso. route'] = cars['Conso. route'].str.split().str.get(0)
# cars['Conso. route'] = cars['Conso. route'].str.replace(',','')


# cars['Conso. route'] = cars['Conso. route'].astype('float')
# cars['Conso. route'].mean()

In [11]:
cars['Volume du réservoir'].unique()

KeyError: 'Volume du réservoir'

In [ ]:
cars['Volume du réservoir'] = cars['Volume du réservoir'].str.split().str.get(0)



cars['Volume du réservoir'] = cars['Volume du réservoir'].astype('float')
cars['Volume du réservoir'].mean()

In [ ]:
cars['Conso. route'].unique()

In [ ]:
cars['Vitesse maxi.'].unique()

In [16]:
cars['Maximum speed'] = cars['Maximum speed'].str.split().str.get(0)



cars['Maximum speed'] = cars['Maximum speed'].astype('float')
cars['Maximum speed'].mean()

208.5467289719626

In [19]:
cars.head(3000)

,Brand,Model,Version,Price,Model year,Hand,Mileage,Fuel type,Transmission,Fiscal horsepower,...,ESP,Traction control,Engine architecture,Engine displacement,City fuel consumption,Highway fuel consumption,Maximum speed,Fuel tank volume,Classe,Année
0,MERCEDES,Classe C 2014,220 d,228.000 DH,2014.0,Seconde,144.500 km,Diesel,Automatique,8 cv,...,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN,Classe C,2014
1,MERCEDES,Classe C 2003,220 CDI,79.000 DH,2003.0,Seconde,350.000 km,Diesel,Manuelle,8 cv,...,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN,Classe C,2003
2,MERCEDES,Classe B 2013,180 d Urban,150.000 DH,2013.0,Seconde,144.000 km,Diesel,Manuelle,8 cv,...,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN,Classe B,2013
3,MERCEDES,Classe E 2006,Autre version,135.000 DH,2006.0,Seconde,248.000 km,Diesel,Automatique,9 cv,...,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN,Classe E,2006
4,MERCEDES,CLA Coupé 2014,220 CDI,240.000 DH,2014.0,Seconde,103.000 km,Diesel,Automatique,9 cv,...,oui,oui,NaN,NaN,NaN,NaN,NaN,NaN,CLA Coupé,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,SEAT,Arona,NaN,248.900 DH * promo,NaN,NaN,NaN,NaN,NaN,6 cv,...,oui,oui,4 cylindres,1.598 cm³,"5,4 l/100 km","4,2 l/100 km",178.0,40 litre,NaN,None
2996,SEAT,Arona,NaN,255.900 DH * promo,NaN,NaN,NaN,NaN,NaN,6 cv,...,oui,oui,4 cylindres,1.598 cm³,"5,4 l/100 km","4,2 l/100 km",178.0,40 litre,NaN,None
2997,SEAT,Ateca,NaN,297.900 DH * promo,NaN,NaN,NaN,NaN,NaN,8 cv,...,oui,oui,4 cylindres,2.998 cm³,"6,2 l/100 km","4,9 l/100 km",202.0,55 litre,NaN,None
2998,SEAT,Ateca,NaN,313.900 DH * promo,NaN,NaN,NaN,NaN,NaN,8 cv,...,oui,oui,4 cylindres,2.998 cm³,"6,2 l/100 km","4,9 l/100 km",202.0,55 litre,NaN,None
2999,SEAT,Ateca,NaN,330.900 DH * promo,NaN,NaN,NaN,NaN,NaN,8 cv,...,oui,oui,4 cylindres,2.998 cm³,"6,2 l/100 km","4,9 l/100 km",202.0,55 litre,NaN,None

In [ ]:
cars['Conso. ville'].mean()

In [ ]:
#Supprimer les colonnes Model et Année
#L'argument inplace dans la fonction drop() est un paramètre booléen qui vous permet de modifier le DataFrame en place,
#sans créer une nouvelle copie du DataFrame.
cars.drop('Model',axis = 1,inplace = True)
cars.drop('Année',axis = 1,inplace = True)
#Imprimer l'en-tête du DataFrame
cars.head()

In [ ]:
cars['Architecture'] = cars['Architecture'].str.replace("cylindres","")
cars['Architecture'] = cars['Architecture'].str.replace("en ligne","")
cars['Architecture'] = cars['Architecture'].str.replace("en V","")
cars['Architecture'] = cars['Architecture'].astype('float')
cars['Architecture'].mean()

In [ ]:
# Remove "DH", ".", "VENDUE", "  ", "*", "promo" and "Prix public" from Prices
cars['Price'] = cars['Price'].str.replace("DH","")
cars['Price'] = cars['Price'].str.replace(".","")
cars['Price'] = cars['Price'].str.replace("VENDUE","")
cars['Price'] = cars['Price'].str.replace("  ","")
cars['Price'] = cars['Price'].str.replace('*', '')
cars['Price'] = cars['Price'].str.replace('promo', '')
cars['Price'] = cars['Price'].str.replace('Prix public', '')
# Convert Prices to float
cars['Price'] = cars['Price'].astype('float')
# Print dtypes again
cars.dtypes

In [ ]:
# Convert Modèle column to datetime
cars['Modèle'] = pd.to_datetime(cars['Modèle'], format='%Y').dt.year
# Print header and datatypes of Modèle column 
print(cars[['Modèle']].head())

In [ ]:
cars.dtypes

In [ ]:
# Remove "cv" and "-" from Puissance fiscale
cars['Puissance fiscale'] = cars['Puissance fiscale'].str.replace("cv","")
cars['Puissance fiscale'] = cars['Puissance fiscale'].str.replace("-","")
# Check for missing values in the "puissance fiscale" column
missing_values = cars["Puissance fiscale"].isna()

# Replace non-numeric values with 0.0
cars["Puissance fiscale"].replace(to_replace=r'[^0-9.]', value='0.0', regex=True, inplace=True)
# Clean non-numeric values
cars["Puissance fiscale"] = pd.to_numeric(cars["Puissance fiscale"], errors="coerce")

# Remove leading and trailing white spaces
cars["Puissance fiscale"] = cars["Puissance fiscale"].apply(lambda x: x.strip() if isinstance(x, str) else x)

# Convert Puissance fiscale to float
cars['Puissance fiscale'] = cars['Puissance fiscale'].astype('float')
# Print header and datatypes of Puissance fiscale column 
print(cars[['Puissance fiscale']])

In [ ]:
cars.dtypes

In [ ]:
# Remove "cm³" and "." from Cylindrée
cars['Cylindrée'] = cars['Cylindrée'].str.replace("cm³","")
cars['Cylindrée'] = cars['Cylindrée'].str.replace(".","")
# Convert Cylindrée to float
cars['Cylindrée'] = cars['Cylindrée'].astype('float')
# Print header and datatypes of Cylindrée column 
print(cars[['Cylindrée']].head())

In [ ]:
cars['Cylindrée'].mean()

In [ ]:
# Visualize la répartition des valeurs manquantes  
msno.matrix(cars)

In [ ]:
# Barplot des valeurs manquantes
msno.bar(cars)

In [ ]:
# Check for duplicate values
print(cars.duplicated().sum())

In [ ]:
# Remove duplicate rows based on all columns
cars = cars.drop_duplicates()

In [ ]:
cars

In [ ]:
# masque booléen pour identifier les valeurs manquantes
mask = cars.isna()

# sélectionner les lignes avec tous les éléments égaux à True
empty_rows = cars[mask.all(axis=1)]

print(empty_rows)

In [ ]:
# Suppression de la ligne 48
cars = cars.drop(index=48)

In [ ]:
cars

In [ ]:
# s'assurer qu'il ne reste plus de ligne avec toutes des valeures manquantes 
mask = cars.isna()
empty_rows = cars[mask.all(axis=1)]

print(empty_rows)

In [ ]:
cars.columns

# Part 2: Data visualization and exploration.

In [ ]:
from matplotlib import pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [ ]:
# Visualiser la répartition des prix 
sns.distplot(cars['Price'], hist=True, bins= 2500, color='r')
plt.xlabel('prices')
plt.title('Distribution of prices')
plt.show()

In [ ]:
#La conversion de la colonne 'Brand' en type 'category' pour faciliter les regroupements et les comptages des données.
cars.Brand = cars.Brand.astype('category')

In [ ]:
#Imprimer les valeurs moyen, max et min des prix
print('le prix moyen est:           ', cars['Price'].mean())
print('Le prix le plus élevé est:   ', cars['Price'].max())
print('Le prix le plus bas est:     ', cars['Price'].min())

In [ ]:
p=plt.hist(cars.Price, bins=2000)

In [ ]:
#créer un graphique de dispersion
j = sns.jointplot(data=movies, x='Price', y='AudienceRating')

In [ ]:
cars['Kilométrage'].mean()